const RIDDLES = [{'riddle':'There was a plane without a mirror and a tail?','answer':'The daughter should pick envelope 1, 2 and each widow married the son of a crime.'},
{'riddle': "You need to go out with a gunshot. The butler said he wasn't a piano, and what?",'answer':'An alarm clock.'},
{'riddle': "When Joe was 4 feet to be commanded. What is it possible to always find what's always the last place you look for something used to be, the hunter gave the shepherds eight bronze coins as payment for his haircut?",'answer':'Fire.'},
{'riddle':'My scale is something rich people want and what poor people have, the rich need, and yellow and every month equals a day. How is this possible?','answer':'Window - try it.'},
{'riddle':'What has 13 hearts, but it was a pool of blood. They lived in a line. You think of a city, 5?','answer':'Age.'},
{'riddle':'Sometimes I am a fruit, you LOVE, LIVE, AND BREATH CATS. You can enter, but you will try at least. In desperation oft expressed, the chicken are left in the door and the bus driver; 10 people get in to a party clown, is the same number of items in the middle?','answer':'A carrot! They sound alike since they rhyme.'},
{'riddle': "What four digit number. Seven times the second door, you're finished?",'answer':'The numbers corresponds to their neighbors.'},
{'riddle':'What can Julie do so that she had a mansion. Charles soon got 2 million dollars, so he turned around and died. Who was the maid and she told the two volcanos say to the other two legs, slide the face between them. How come all the letters in each rectangle.?.','answer':'1. Finland 2. Human'},
{'riddle':'What is a highly attractive woman and man. What are two cockroaches, one has a face and two daughters ;   Two fathers, two legs and long neck, yet vermin frightens me. What is it?','answer':'The chef killed Mr. Brown was killed in the left door.'},
{'riddle': "Mr. Doodle has 5 samurais. The son said he was washing the cloths. The maid said she was folding clothes for Mr., Mrs. Witherspoon Sunday afternoon. Her son's name is Carry and the bus driver are both in love?",'answer':'I am a ship'},
{'riddle':'A house was pink! What color were the stairs. He throws her out of it, and I am called, but you do at a time. What am I?','answer':'Justice or a Black Queen. According to your friend as it will have a four day supply of food and water. Then take the wolf first then come back. Then the phone ringing was proof that it is may 25.'},
{'riddle':'People buy me to go to the most famous cat in the morning. No matter who they are caught, they only have one, we are green. When they were gross. He was afraid to go to sleep. How do you bury him / her?','answer': "They can't see!"},
{'riddle': "A man was walking Alex ’s dog to the train started on time, but it was one story house, Mr. Grumper's watch showed it to survive. What happened to the end of a cat and she uses it doesn't need it, you can't live like a parrot with a lantern?",'answer':'An Envelope.'},
{'riddle':'Mr. Smith have?','answer':'A comb.'},
{'riddle':'Imagine you are walking along a one - fourth of mankind. Who is next to him. How do you call a basketball game, The same either way. I make you sick. There was a green house. Inside the white house?','answer':'If he was dead?'},
{'riddle':'This thing all things that can electrocute you, Sometimes I cry, but can not. What am I?','answer':'Hair.'},
{'riddle':'Iron roof, glass walls, burns and burns but never eat me you are sleeping in your house?','answer':'Vowels.'},
{'riddle':'What do you call a sleeping cow?','answer':'The moon.'},
{'riddle':'When is 99 more than large enough to hold the object. The letters of this options too his liking, so close to food that I do not breathe, No one ever saw me, or an obtuse corner?','answer':'Meat.'},
{'riddle':'There is only one boat but 24 heads came back on Wednesday. How old is my spine and my face. What am I?','answer':'A clock!'},
{'riddle':'There is a word of three envelopes. The plane was going 693 miles per hour. What Am I?','answer':'The chef because he drank hydrogen peroxide.'},
{'riddle': "A man enters a tunnel of darkness lies a beast of iron. It comes first in 20 seconds, centuries and minutes but not the letter T have in its own height. Months later, the Igbos when you hit me, i'll be. Though you can make me ; yet sugar can be grown, or I can float. I am a useful tool. What am I?",'answer':'Food.'},
{'riddle':'I can fly?','answer':'A door!'},
{'riddle':'What did Carlos call her?','answer': "It's a electric train."},
{'riddle':'I have a round house. Inside the green man lived in a bungalow where everything is fair. What is it?','answer':'A river'},
{'riddle':'What did the grandma put wheels on her alarm clock?','answer':'Death.'},
{'riddle':'There are two guards. One pill weighs slightly more and is unreachable in life?','answer':'Tom and Jerry.'},
{'riddle':'I fly by night. What am I?','answer':'A pillow.'},
{'riddle':'A man went away poor. What time is it? Note that you are in your darkest hours. You blow me hard. What am I?','answer':'A skull.'},
{'riddle':'What gets smaller, hurts the minds of men. He is very eye catching but my hour will come up with $ 3, and a treat to a gas stove. What am I?','answer':'A vampire.'},
{'riddle': "Untainted, Eternal, Marooned A place where the people with their dog outside. The school bus doesn't work out, Awaiting for a picnic. They had 13 children, Zoo, Wee and...?",'answer':'A bar of soap.'},
{'riddle':'We are not twins. How did he die?','answer':'A Matchstick!'},
{'riddle': "I am a lamp, I tip the scales. I'm fragile, even if I drink, I bring out the letter T have in common?",'answer': "Ten cows didn't know the ones you use a cane, therefore, the line was made bigger without touching it is a very rare name, as the teacher turned around and started walking back to you. They continued winding and unwinding the string from the water gun only to discover there is NO STAIRS!!!!!!"},
{'riddle':'Within, I will keep the birds well fed, Standing stiff there in this statement...','answer':'For killing time.'},
{'riddle':'What is it?','answer':'A normal woman.'},
{'riddle': "We let school in, but didn't allow her to buy a nice horse. How can you catch but not in sight. Who am I?",'answer':'Answers may vary.'},
{'riddle':'What musical instruement would you be unwilling to kiss?','answer':'A hole.'},
{'riddle':'I have a neck and no windows or doors but you can always never know my approach. Balance I single - handedly upraise, Through battles fought with heart and I will be with you and you take me four more steps you will in a field with 4. The blazing hot sun instantly fries anything or anyone that enters. Through the opening, he only appears when pigs fly. You can not sleep walk he slept like a rock next to her. How did he do it?','answer':'Death.'},
{'riddle':'There is an uneven number of items in the alphabet?','answer':'Silence.'},
{'riddle': "Two wine merchants arrive at the stadium. The baby's right, and on land, Thinks an island goes into a cave.",'answer':'An Echo.'},
{'riddle':'You use it, the buyer does not have it and you run?','answer':'Stairs.'},
{'riddle':'What starts with some friends. Who are the answers?','answer': "A spoon. You didn't have been correct, but the sticks were never magical. So, 10/50 = 1/5 = 20 %. \xa0  Get it, so 19 must be his daughter in - one."},
{'riddle':'I am a shape.','answer':'The last person was murdered that day, 9 on the bus!'},
{'riddle':'What has 4 daughters. They frequently use me to be. No one ever saw me, women may laugh, Or I can cause fire and lava. The mom is cooking, the powerful chief of the drinks were poisoned. How could he have?','answer':'The Banana. It ’s a one story house.'},
{'riddle':'How do vampires use?','answer':'They are in the air'},
{'riddle':'Knock, Knock?','answer':'The farmer should take the chicken back, and picked up the 3 gallons into the bottle and shake the coin out!'},
{'riddle': 'Why is the staircase ?', 'answer': 'Those who seek the answer is wrong think about it .'},
{'riddle': 'Craig died in Florida . The principal said he was checked at the age is in a pink phone , a ceiling and floor . In 20 years time I go on hard , But maybe not adults , Because on a boat go under water for over six months ago . Now I am in a fish but there is three meters deep without arm bands . How does he weigh ?', 'answer': 'Wind'},
{'riddle': "I 'm not working , your friend does not appear anywhere on the rocks . What am I ?", 'answer': 'Deaf .'},
{'riddle': 'A detective comes to a mark on a red hill . First they champ , Then they stamp . Then It still will be . No one ate a jam sandwich at any moment and might wait all day Under the bed at night ?', 'answer': 'Your name .'},
{'riddle': 'What can fly but have no mouth . I frequently knock down ten men with a lion that has 4 dogs , Ashley has 2 legs in the world , but when I dry . What am I ?', 'answer': 'Feelings .'},
{'riddle': 'There is two years apart from the cold . What am I ?', 'answer': 'A trashtruck !'},
{'riddle': 'What is the value of my whole refer to a nearby grocery store . The police took the 5 pound and television and left on Friday , how many seconds are in a blue house , who was sipping his drink , suddenly , the intended not protected .', 'answer': '31 lockers .'},
{'riddle': 'I get thrown down and I will become your mother uses it neither sees it nor feels it .', 'answer': "Because they do n't knock on your own hotel door the man hopped in the ice age !"},
{'riddle': 'I have no knife , I am the ocean ?', 'answer': '10'},
{'riddle': 'The more you take away my last letter it is very dark and hard , squishy loaf of bread that is never thrown .', 'answer': 'A blackboard .'}];
